reads_dir:
samples: []
meangs_path: '/PUBLIC/software/Disease/suqingdong/software/bio/meangs/MEANGS-master'
organelle_database: 'animal_mt'
genome_min_size: 12000
genome_max_size: 22000
kmer_size: 39
max_mem_gb: 10
read_length: 150
insert_size: 300
clade: 'Annelida-segmented-worms'
genetic_code: 5
thread_number: 20
result_dir: 'result'

reference:
genes:
