name: FastMitoAssembler

channels:
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python==3.9.*
  - snakemake
  - NOVOPlasty
  - GetOrganelle
  - spades
  - blast
  - mitoz
  - seqkit
  - click
  - flask
  - jinja2
  - pyyaml
