name: FastMitoAssembler

channels:
  - conda-forge
  - bioconda
  - yccscucib
  - defaults

dependencies:
  - python==3.9.*
  - pip
  - snakemake
  - NOVOPlasty
  - GetOrganelle
  - spades
  - blast
  - mitoz
  - seqkit
  - meangs
  - pip:
    - click
    - flask
    - jinja2
    - pyyaml
    - genbank

